# Vectorization

In [2]:
arr = [1,2,3]
print(arr*5)
arr = [x*5 for x in arr] #SISD
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [3]:
import numpy as np
arr1 = np.array([1,2,3])
arr1 = arr1*5 #SIMD

print(arr1)

[ 5 10 15]


## Ndarray


In [4]:
import numpy as np

#1d array

arr1 = np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim)

<class 'numpy.ndarray'>
1


In [5]:
#2d array

arr2 = np.array([[1,2,3], #row1
                  [4,5,6] #row2
                 ])

print(arr2.ndim)

2


In [6]:
#3d array - akta array r moddhe onekgula 2d array

arr3 = np.array([

    #1st floor
    [[1,2,3],
     [4,5,6]],

    #2nd floor
    [[6,7,8],
     [9,10,11]],

    #3rd floor
    [[1,2,3],
     [4,5,6]],

    #4th floor
    [[6,7,8],
     [9,10,11]]
])

print(arr3.ndim)

3


## Attributes


In [7]:
#dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape -> tuple (row,column)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape) # (floor, row,column)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size -> total koyta value ase
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(4, 2, 3)
int64
int64
int64
5
6
24


## Data Types

In [8]:
arr = np.array([1,2,3])
print(arr.dtype)

arr = np.array([11.2,1.3,22.0])
print(arr.dtype)

arr = np.array(["sadman","tutu","kutu"])
print(arr.dtype) #U -> Unicode

int64
float64
<U6


Upcasting

In [9]:
arr = np.array([1,2,3.5])
print(arr.dtype) # upcasted to float

arr = np.array([2.5,3,'3'])
print(arr.dtype) # upcasted to string

float64
<U32


Selecting a datatype

In [10]:
#using dtype
arr = np.array([1,2,3],dtype=np.int32)
print(arr.dtype)

#using astype

arr = np.array([1,2,3])
print(arr.dtype)

arr = arr.astype(np.float64)
print(arr.dtype)

int32
int64
float64


Ndarray creation from existing array

In [11]:
lst = [1,2,3,4,5]
arr = np.array(lst)
print(arr)
print(arr.dtype)

mixed_lst = [10,True, "Hello", 10.5]
matrix = [[1,2,3],[1,2,3]]
arr = np.array(matrix)
print(type(arr))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]]
int64
(2, 3)
2


In [12]:
#tuple

tpl = (10,20,30)
arr = np.array(tpl)
print(type(arr))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

<class 'numpy.ndarray'>
[10 20 30]
int64
(3,)
1


In [13]:
#set

st = {1,2,3}
arr = np.array(list(st)) # list e convert korte hoi
print(type(arr))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


<class 'numpy.ndarray'>
[1 2 3]
int64
(3,)
1


In [14]:
#dictionary

dc = {'a': 10, 'b': 20, 'c' : 30}

print(type(dc))

keys = dc.keys()
values = dc.values()
print(values)
items = dc.items()
print(items)

<class 'dict'>
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [15]:
#keys to ndarray
arr = np.array(list(keys))
print(type(arr))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

<class 'numpy.ndarray'>
['a' 'b' 'c']
<U1
(3,)
1
3


In [16]:
#values to ndarray
arr = np.array(list(values))
print(type(arr))
print(arr)
arr = arr.astype(np.int32)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

<class 'numpy.ndarray'>
[10 20 30]
int32
(3,)
1
3


In [17]:
#items to ndarray
arr = np.array(list(items))
print(type(arr))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

<class 'numpy.ndarray'>
[['a' '10']
 ['b' '20']
 ['c' '30']]
<U21
(3, 2)
2
6


# Creating ndarray from scratch

In [18]:
arr = np.zeros((2,3)) # shape (2,3) tuple
arr = arr.astype(np.int64)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
int64
(2, 3)
2
6


In [19]:
#zeros like

arr = np.zeros_like(arr3)
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(4, 2, 3)


In [20]:
#np ones
arr = np.ones((4,3)) # shape (4,3) tuple
arr = arr.astype(np.int64)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int64
(4, 3)
2
12


In [21]:
#ones like
arr = np.ones_like(arr3)
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(4, 2, 3)


In [22]:
#np empty
arr = np.empty((4,3)) # shape (4,3) tuple
arr = arr.astype(np.int64)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
int64
(4, 3)
2
12


In [23]:
#empty like
arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(4, 2, 3)


In [24]:
#np full
arr = np.full((4,3),fill_value=10) # shape (4,3) tuple
arr = arr.astype(np.int64)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
int64
(4, 3)
2
12


In [25]:
#empty like
arr = np.full_like(arr3, np.inf,dtype=np.float64)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
float64
(4, 2, 3)
3
24


# Array creation from random values

In [26]:
arr = np.random.rand(2,3) #0-> 1
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.09549206 0.2305614  0.24379676]
 [0.09449862 0.75987154 0.59218931]]
float64
(2, 3)
2
6


In [27]:
#np.random.randint(start,end,shape)
arr = np.random.randint(1,10,(21,10))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[7 5 4 1 5 5 9 4 9 3]
 [3 3 2 2 2 2 7 7 9 4]
 [8 5 2 9 1 1 1 9 1 9]
 [5 5 6 1 8 5 9 9 6 8]
 [3 6 8 2 9 6 7 5 8 6]
 [1 9 4 3 7 5 4 4 3 9]
 [2 2 9 3 3 1 4 3 1 9]
 [1 4 3 9 4 8 5 5 9 7]
 [3 2 5 3 8 3 8 6 8 8]
 [9 8 1 3 8 3 9 2 8 9]
 [7 8 1 3 1 2 7 6 8 3]
 [9 2 9 9 9 9 5 7 9 4]
 [2 2 6 2 4 3 9 6 1 4]
 [2 3 2 4 7 7 3 4 4 3]
 [3 1 6 7 4 7 5 4 7 4]
 [2 4 2 4 5 2 2 5 8 8]
 [9 4 4 1 3 9 9 6 9 8]
 [7 8 3 3 7 1 9 8 4 7]
 [7 4 9 1 2 4 9 3 5 1]
 [1 9 4 7 2 7 2 4 5 9]
 [7 8 7 5 9 1 2 5 5 3]]
int64
(21, 10)
2
210


In [28]:
#np.random.uniform(start,end,shape)
arr = np.random.uniform(50,100,(5,5))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[65.61809325 79.577298   87.29839313 72.14186811 99.19445412]
 [59.66666775 83.01689746 93.13805276 96.53873059 89.7400096 ]
 [75.58901201 96.88409711 74.93678403 59.99206518 59.14825757]
 [56.47059164 83.35637521 95.90439163 89.9043743  54.59761703]
 [86.96805809 72.54608738 59.33857713 63.47082071 72.83110471]]
float64
(5, 5)
2
25


# Array generation with range(Nirdisto)

In [29]:
#np.arange(start,end,step)
arr = np.arange(1,10,1)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
int64
(9,)
1
9


In [30]:
matrix = arr.reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
#np.linspace(start,end,koita) -> start end k evenly distribute kore based on koita

arr= np.linspace(1,10,15)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
float64
(15,)
1
15


In [32]:
#np.logspace(start,end(included),koita) -> sob value nibe but 10 er powe e bosai dibe

arr = np.logspace(0,4,5)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


# Creating Matrix for Linear Algebra

In [38]:
diagonal = np.diag([1,2,3,4])
print(diagonal)
print(diagonal.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [40]:
#identity
identity_mat = np.eye(4) # 4x4
print(identity_mat)
print(identity_mat.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [42]:
mat = np.eye(3,4) # 3x4
print(mat)

# np.eye(row , column,k)
mat = np.eye(3,4,2)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


Indexing and slicing

In [33]:
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [36]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
#slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2   3 200]
[1 2 3 4 5]


In [44]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2)

#getting a row

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion


portion = arr2[:: , 0:2]

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


Advanced Slicing

In [45]:
lst = np.array([ 10 , 20 ,30 ,40 ])

values = lst[[0,3,1]] # index

print(values)

[10 40 20]


In [ ]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr>1])
arr2[arr2>2] = 0

print(arr2)

In [49]:
arr = np.array([[10,20,30],[100,200,300]])
 #iteration
print(arr)
for i in np.nditer(arr):
  print(i)

[[ 10  20  30]
 [100 200 300]]
10
20
30
100
200
300
