In [1]:
import numpy as np

# Array Manipulation

In [2]:
arr = np.random.randint(1,100,size=(10,5)) # sample - 10, feature - 5
print(arr)
print(arr.shape)

[[44 92 11 45 94]
 [63 35 25 15 58]
 [36 70 29 18 29]
 [34 11 99 94 66]
 [77 78 46 94 94]
 [ 8 43 51 28 57]
 [71 68 18 54 95]
 [97 28  8 80 16]
 [86  6 30 16 92]
 [ 2 89 34  2 37]]
(10, 5)


In [3]:
#change shape
#ensure jei shape ta tara chacche oita amar existing shape theke banano possible ki na
#jemon 5x10 k 25 x 2 te shape kora jabe kintu 10x2 te kora jabe na

b = arr.reshape(5,10)
print(b)
print(b.shape)

[[44 92 11 45 94 63 35 25 15 58]
 [36 70 29 18 29 34 11 99 94 66]
 [77 78 46 94 94  8 43 51 28 57]
 [71 68 18 54 95 97 28  8 80 16]
 [86  6 30 16 92  2 89 34  2 37]]
(5, 10)


In [4]:
flatten = b.flatten()
print(flatten)
print(flatten.ndim)

[44 92 11 45 94 63 35 25 15 58 36 70 29 18 29 34 11 99 94 66 77 78 46 94
 94  8 43 51 28 57 71 68 18 54 95 97 28  8 80 16 86  6 30 16 92  2 89 34
  2 37]
1


In [5]:
column_wise_flattening = np.ravel(b,order='F')
column_wise_flattening


array([44, 36, 77, 71, 86, 92, 70, 78, 68,  6, 11, 29, 46, 18, 30, 45, 18,
       94, 54, 16, 94, 29, 94, 95, 92, 63, 34,  8, 97,  2, 35, 11, 43, 28,
       89, 25, 99, 51,  8, 34, 15, 94, 28, 80,  2, 58, 66, 57, 16, 37])

In [6]:
row_wise_flattening = np.ravel(b,order='C')
row_wise_flattening

array([44, 92, 11, 45, 94, 63, 35, 25, 15, 58, 36, 70, 29, 18, 29, 34, 11,
       99, 94, 66, 77, 78, 46, 94, 94,  8, 43, 51, 28, 57, 71, 68, 18, 54,
       95, 97, 28,  8, 80, 16, 86,  6, 30, 16, 92,  2, 89, 34,  2, 37])

In [7]:
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size=(2,3))


In [8]:
a

array([[4, 4, 9],
       [3, 5, 9]])

In [9]:
b

array([[27, 23, 20],
       [26, 28, 23]])

# Concatenate

In [10]:
#row wise
con_row = np.concatenate((a,b),axis=0) # axis=0 rowwise
con_row

array([[ 4,  4,  9],
       [ 3,  5,  9],
       [27, 23, 20],
       [26, 28, 23]])

In [11]:
#column wise
con_col = np.concatenate((a,b),axis=1) # axis=1 colwise
con_col

array([[ 4,  4,  9, 27, 23, 20],
       [ 3,  5,  9, 26, 28, 23]])

Row wise concat korar somoy colum er dim same thakte hobe \n
col wise concat korar somoy row er dim same thakte hobe

a = 2x3 b = 1x3 . concat(a,b) possible

In [12]:
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size=(1,3))
con_row = np.concatenate((a,b),axis=0) # axis=0 rowwise
con_row

array([[ 8,  4,  5],
       [ 8,  5,  2],
       [21, 26, 27]])

In [13]:
#Transpose
mat = np.array([[10,20,30],
               [40,50,60]])
transpose = mat.T
transpose

array([[10, 40],
       [20, 50],
       [30, 60]])

Array split


In [14]:
a = np.random.randint(1,10,size=(10,))
a

array([8, 1, 5, 2, 7, 6, 6, 6, 5, 7])

In [15]:
splitted_array = np.array_split(a,3)
print(splitted_array) #10 ta value tai 1st row te akta value asche
#array_split = inequal
splitted_array

[array([8, 1, 5, 2]), array([7, 6, 6]), array([6, 5, 7])]


[array([8, 1, 5, 2]), array([7, 6, 6]), array([6, 5, 7])]

In [16]:
#error
#np.split = equal split
# splitted_array = np.split(a,3) # error karon 10 ta value 3 ta equal row te convert kora possible na

# Arithmaric Operator and Math Function

In [17]:
#faster for vectorization
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = np.add(x,y)
print(add)
sub =np.subtract(x,y)
print(sub)
mul = x*y
print(mul)
div = x/y
print(div)
reminder = x%y
print(reminder)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [18]:
#mathmatical function

#trigonometry
sin_val = np.sin(x) # takens value in radian
print(sin_val)
cos_val = np.cos(x)
print(cos_val)
tanval = np.tan(x)
print(tanval)


#convert to degree
deg_con = np.rad2deg(x)
print(deg_con)

#deg2red


[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [19]:
#log

base_10_log_val = np.log10(x) # kono akta value k 10 diye koybar vag korte parbo
base_10_log_val

two_diye_kobar_vag_kora_jay = np.log2(8)
print(two_diye_kobar_vag_kora_jay)

3.0


In [20]:
#sqrt
r = np.sqrt(x)
r

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [21]:
print(np.sum(x))
print(np.cumsum(x))

100
[ 10  30  60 100]


Logical

In [22]:
#comparison >, < , >= , <= , == , !=
x = np.array([10,8,16,100])
y = np.array([2,3,4,5])

In [23]:
x>y

array([ True,  True,  True,  True])

In [24]:
x< y

array([False, False, False, False])

In [25]:
x== y

array([False, False, False, False])

In [26]:
#np.all() -> sob gula true kina
#np.any() -> jekono akta true kina

print(np.all(x>y))
print(np.any(x< y))

True
False


# Sorting

In [27]:
x = np.random.randint(1,100,7)
z = x.copy()

#inplace sort
z.sort()
print(x)
print(z)

[ 3 37 11 54 29 22  3]
[ 3  3 11 22 29 37 54]


In [28]:
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[ 3 37 11 54 29 22  3]
[ 3  3 11 22 29 37 54]
[ 3 37 11 54 29 22  3]


In [29]:
#2d soring
mat = np.array([[10,3,4],[8,4,9]])

#row wise sorting
hor_sort = np.sort(mat,axis=1)

#col wise sorting
var_sort = np.sort(mat, axis=0)

print(hor_sort)
print(var_sort)

[[ 3  4 10]
 [ 4  8  9]]
[[ 8  3  4]
 [10  4  9]]


Searching

In [30]:
print(x)

[ 3 37 11 54 29 22  3]


In [31]:
#np.where(condition, x,y) if true x, otherwise replace with y
index = np.where(x==8)
print(index)

index = np.where(x>50,x,0)
print(index)

(array([], dtype=int64),)
[ 0  0  0 54  0  0  0]


In [32]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [33]:
import numpy as np
x = np.array([10,100,8,16,100])

max_val_index = np.argmax(x)
min_val_index = np.argmin(x)
print(max_val_index)
print(min_val_index)

1
2


Counting in Nparray

In [34]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[45 44 58 17 28 63 75  3 75 67 38 63 11 88 92 44 72 54 10 35 67 19 90 82
 96 27 18 80 28 31 49 91 19 60 69 90 16 42  4 32 61 26 25 44 82 49  7 97
 20 79 18 87 10 96 26 35 61 44 42 30 83 91 96 66 75 87 70 10 15 12 47 49
 88 40 95  8 14 38 56 22 60 50 15 91 41  9 83 83 34 94  6  8 24  6 57 72
 80 55 40 70]


In [35]:
value_great_than_60 = np.count_nonzero(a> 60) # koita value ase
print(value_great_than_60)

39


In [36]:
unique_value,count = np.unique(a,return_counts=True)
print(unique_value)
print(count)

[ 3  4  6  7  8  9 10 11 12 14 15 16 17 18 19 20 22 24 25 26 27 28 30 31
 32 34 35 38 40 41 42 44 45 47 49 50 54 55 56 57 58 60 61 63 66 67 69 70
 72 75 79 80 82 83 87 88 90 91 92 94 95 96 97]
[1 1 2 1 2 1 3 1 1 1 2 1 1 2 2 1 1 1 1 2 1 2 1 1 1 1 2 2 2 1 2 4 1 1 3 1 1
 1 1 1 1 2 2 2 1 2 1 2 2 3 1 2 2 3 2 2 2 3 1 1 1 3 1]


# Linear Algebra

In [37]:
import numpy as np # Re-import numpy to restore np.array function
sq_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

det_of_sq = np.linalg.det(sq_mat)
rank_sq = np.linalg.matrix_rank(sq_mat)
print(det_of_sq)
print(rank_sq)

0.0
2


In [38]:
print(type(np))
print(type(np.array))

<class 'module'>
<class 'builtin_function_or_method'>


In [39]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
